platform :ios, '10.0'


flutter_application_path = '../one_day_flutter'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'one_day_ios' do
  
  pod 'YTKNetwork'
  install_all_flutter_pods(flutter_application_path)

  

end

post_install do |installer|
  flutter_post_install(installer) if defined?(flutter_post_install)
end
